"""Built-in post-import compatibility patches for vLLM on Kunlun XPU.

Every patch here exists for the same underlying reason: upstream vLLM
assumes CUDA (or Triton) somewhere, and Kunlun XPU needs a different or
no-op behavior at that spot.

Each patch is a pair of functions operating on the target vLLM module:

- ``*_applied(module)`` reports whether the patch is already in effect.  It
  must also return True when the patch is not needed for this vLLM version,
  so missing attributes are treated as "nothing to do", not as errors.
- ``_apply_*(module)`` performs the patch exactly once.

Two patching styles appear below:

1. Direct: ``_apply_*`` modifies the module attribute itself.
2. Import-for-side-effect: ``_apply_*`` contains only an import statement.
   The imported Kunlun module patches the upstream object when it loads and
   marks it with a ``_kunlun*_patched`` attribute, which the ``*_applied``
   predicate checks.  When you see a lone import, the real patch logic lives
   in that module.

To add a new patch: write an ``*_applied`` / ``_apply_*`` pair following the
conventions above, then append one entry to ``DEFAULT_HOOKS`` at the bottom.
``import_hooks`` registers the table with the dispatcher at import time.

The Model Runner V2 patches near the bottom are all import-for-side-effect and
share one shape, so their pairs are generated by ``_v2_hook`` from the
``_V2_PATCHES`` table rather than written out fourteen times.  The V2 *gate*
(``vllm.config.vllm``) is a direct patch at the top of this file.
"""

import functools
import importlib
import logging
import sys
from types import ModuleType

# --- vllm.config.vllm: lift the Model Runner V2 Triton veto ---------------
#
# Kunlun swaps the V2 Triton kernels for torch-native / kunlun_ops equivalents
# (the ``vllm.v1.worker.gpu.*`` patches below), and ``vllm.config.vllm`` reads
# ``HAS_TRITON`` only to veto V2, so forcing it True has no other side effect.
# It has to be a post-import patch: ``check_and_update_config`` runs only from
# ``VllmConfig.__post_init__``, which does not re-run in EngineCore, so patching
# there landed after ``gpu_worker.py`` had already fallen back to V1.
# VLLM_USE_V2_MODEL_RUNNER is deliberately left unset -- setting it makes the
# property early-return past upstream's own filters, which is how hybrid
# Qwen3.5 reached V2 and died importing ``model_states.mamba_hybrid``.


def _mrv2_gate_applied(module: ModuleType) -> bool:
    """Return whether the V2 gate is installed, or the module predates it."""
    if not hasattr(module, "HAS_TRITON"):
        return True
    return getattr(module, "_kunlun_v2_gate_installed", False)


def _apply_mrv2_gate(module: ModuleType) -> None:
    """Force ``HAS_TRITON`` True and reject the V2 paths Kunlun cannot run."""
    module.HAS_TRITON = True

    orig_unsupported = module.VllmConfig._get_v2_model_runner_unsupported_features

    @functools.wraps(orig_unsupported)
    def _kunlun_mrv2_unsupported_features(self) -> list[str]:
        # These paths still depend on unsupported Triton kernels.
        import vllm.envs as envs

        unsupported = orig_unsupported(self)

        if self.speculative_config is not None:
            unsupported.append(
                "speculative decoding (Kunlun XPU P800 has no Triton and the "
                "V2 rejection-sampler kernels are not replaced yet)"
            )

        if self.parallel_config.decode_context_parallel_size > 1:
            unsupported.append(
                "decode context parallelism (not replaced on Kunlun XPU P800)"
            )

        if (
            self.cache_config is not None
            and self.cache_config.mamba_cache_mode == "align"
        ):
            unsupported.append(
                "mamba align cache mode (its Triton launch sites are not "
                "replaced on Kunlun XPU P800)"
            )

        if envs.VLLM_COMPUTE_NANS_IN_LOGITS:
            unsupported.append(
                "VLLM_COMPUTE_NANS_IN_LOGITS (not replaced on Kunlun XPU P800)"
            )

        return unsupported

    module.VllmConfig._get_v2_model_runner_unsupported_features = (
        _kunlun_mrv2_unsupported_features
    )
    module._kunlun_v2_gate_installed = True
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] Opened the Model Runner V2 Triton gate and installed "
        "the Kunlun capability gate (upstream still decides whether V2 is used)."
    )


# --- vllm.utils.import_utils: do not probe CUDA-only optional deps ---------
#
# ``_has_module`` decides availability with a trial import and logs a WARNING
# plus a full traceback when that import fails.  For a library shipped only as
# CUDA binaries the failure is certain on Kunlun (DeepGEMM dies on
# ``libcudart.so.13``), so the traceback is noise in every startup log.
# Answering False without importing is the same verdict, quietly.
#
# It cannot be left to ``VLLM_USE_DEEP_GEMM``: upstream evaluates
# ``envs.VLLM_USE_DEEP_GEMM and has_deep_gemm() and is_supported_arch``
# (``utils/deep_gemm.py``), so the probe runs before the platform's own
# ``support_deep_gemm()`` verdict is consulted -- turning the flag off would
# work, but it means overriding a user-intent switch to state a hardware fact.
#
# Patching ``_has_module`` rather than ``has_deep_gemm`` is deliberate: many
# modules do ``from vllm.utils.import_utils import has_deep_gemm``, so that
# name is already bound by value in each of them, while ``has_deep_gemm``
# itself resolves ``_has_module`` from module globals on every call.

_CUDA_ONLY_MODULES = frozenset(
    {
        # DeepGEMM: JIT-compiled FP8 CUDA kernels for Hopper/Blackwell.  Kunlun
        # has vllm_kunlun.ops.deep_gemm, which reuses only the interface.
        "deep_gemm",
        "vllm.third_party.deep_gemm",
    }
)


def _optional_dep_probe_applied(module: ModuleType) -> bool:
    """Return whether the probe is filtered, or the module predates it."""
    if not hasattr(module, "_has_module"):
        return True
    return getattr(module, "_kunlun_dep_probe_installed", False)


def _apply_optional_dep_probe(module: ModuleType) -> None:
    """Answer False for CUDA-only modules instead of trial-importing them."""
    original = module._has_module

    @functools.wraps(original)
    def _kunlun_has_module(module_name: str) -> bool:
        if module_name in _CUDA_ONLY_MODULES:
            return False
        return original(module_name)

    module._has_module = _kunlun_has_module
    module._kunlun_dep_probe_installed = True
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] Reporting CUDA-only optional dependencies as "
        "unavailable without importing them: %s",
        ", ".join(sorted(_CUDA_ONLY_MODULES)),
    )


# --- vllm.v1.worker.utils: replace KVBlockZeroer --------------------------


def _kv_block_zeroer_applied(module: ModuleType) -> bool:
    """Return whether ``KVBlockZeroer`` is absent or already patched."""
    cls = getattr(module, "KVBlockZeroer", None)
    return cls is None or getattr(cls, "_kunlun_patched", False)


def _apply_kv_block_zeroer(module: ModuleType) -> None:
    """Import the Kunlun module whose side effect patches ``KVBlockZeroer``."""
    if hasattr(module, "KVBlockZeroer"):
        import vllm_kunlun.v1.worker.utils  # noqa: F401


# --- vllm.v1.attention.backends.mla.prefill.registry: claim CUSTOM --------
#
# vLLM's automatic MLA prefill selection only walks CUDA/ROCm backends, so
# `MLAAttention.__init__` raises "No valid MLA prefill backend found" on Kunlun
# and no MLA model loads at all.  `KunlunPlatform.check_and_update_config`
# selects CUSTOM, but the registry's override dict is per-process and that hook
# runs only in the API server, so every worker has to claim the slot itself.
#
# A post-import patch rather than a bootstrap stage: `vllm.v1.attention...` is
# not importable during plugin registration.  Registering by dotted path keeps
# the Kunlun class unimported until something asks for it.

_KUNLUN_MLA_PREFILL_PATH = (
    "vllm_kunlun.v1.attention.backends.mla.prefill.KunlunMLAPrefillBackend"
)


def _mla_prefill_backend_applied(module: ModuleType) -> bool:
    """Return whether the CUSTOM slot is taken, or the registry is absent."""
    backend_enum = getattr(module, "MLAPrefillBackendEnum", None)
    overrides = getattr(module, "_MLA_PREFILL_OVERRIDES", None)
    if backend_enum is None or overrides is None:
        return True
    return backend_enum.CUSTOM in overrides


def _apply_mla_prefill_backend(module: ModuleType) -> None:
    """Point the registry's CUSTOM slot at the Kunlun prefill backend."""
    register = getattr(module, "register_mla_prefill_backend", None)
    backend_enum = getattr(module, "MLAPrefillBackendEnum", None)
    if register is None or backend_enum is None:
        return
    register(backend_enum.CUSTOM, _KUNLUN_MLA_PREFILL_PATH)


# --- vllm.v1.worker.gpu_model_runner: tolerant bind_kv_cache --------------
#
# `gpu_model_runner` binds `bind_kv_cache` into its own namespace at import
# time, so patching `vllm.v1.worker.utils` is not enough -- the already-bound
# name has to be replaced here.  See the docstring on the replacement for why
# DSA models need it.


def _bind_kv_cache_applied(module: ModuleType) -> bool:
    """Return whether ``bind_kv_cache`` is absent or already Kunlun's."""
    fn = getattr(module, "bind_kv_cache", None)
    if fn is None:
        return True
    return getattr(fn, "__module__", "").startswith("vllm_kunlun")


def _apply_bind_kv_cache(module: ModuleType) -> None:
    """Swap in the Kunlun ``bind_kv_cache`` that allows shared layer indices."""
    if not hasattr(module, "bind_kv_cache"):
        return
    from vllm_kunlun.v1.worker.utils import bind_kv_cache

    module.bind_kv_cache = bind_kv_cache


# --- vllm.model_executor.models.qwen3_vl: disable Triton kernels ----------


def _qwen3_vl_applied(module: ModuleType) -> bool:
    """Return whether Triton has already been disabled for Qwen3-VL."""
    return not getattr(module, "HAS_TRITON", False)


def _apply_qwen3_vl_patch(module: ModuleType) -> None:
    """Force the non-Triton code path; Triton kernels cannot run on Kunlun."""
    module.HAS_TRITON = False
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] qwen3_vl HAS_TRITON forced to False"
    )


# --- vllm.model_executor.layers.minimax_rms_norm.rms_norm_tp: no Triton ---


def _minimax_rms_norm_tp_applied(module: ModuleType) -> bool:
    """Return whether MiniMax's unsupported CUDA and Triton paths are disabled."""
    return (
        not getattr(module, "HAS_TRITON", False)
        and getattr(module, "_MINIMAX_FUSED_AR_RMS_QK", None) is None
    )


def _apply_minimax_rms_norm_tp_patch(module: ModuleType) -> None:
    """Disable MiniMax CUDA fusion and use the eager QK-RMSNorm fallback.

    MiniMax selects the fused CUDA all-reduce/RMSNorm custom operator when
    ``_MINIMAX_FUSED_AR_RMS_QK`` is available.  Otherwise its fallback uses
    Triton when ``HAS_TRITON`` is true.  Kunlun supports neither path, so both
    gates must be disabled to reach the eager all-reduce plus RMSNorm path.
    """
    module.HAS_TRITON = False
    if hasattr(module, "_MINIMAX_FUSED_AR_RMS_QK"):
        module._MINIMAX_FUSED_AR_RMS_QK = None
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] disabled MiniMax RMSNorm Triton and fused CUDA paths"
    )


# --- vllm.v1.worker.block_table: patch slot-mapping computation -----------


def _block_table_applied(module: ModuleType) -> bool:
    """Return whether ``BlockTable`` is absent or has Kunlun slot mapping."""
    cls = getattr(module, "BlockTable", None)
    return cls is None or getattr(cls, "_kunlun_slot_patched", False)


def _apply_block_table_patch(module: ModuleType) -> None:
    """Import the Kunlun ``BlockTable`` implementation for its patch effect."""
    if hasattr(module, "BlockTable"):
        import vllm_kunlun.v1.worker.block_table  # noqa: F401


# --- vllm.v1.structured_output.utils: replace apply_grammar_bitmask -------


def _grammar_bitmask_applied(module: ModuleType) -> bool:
    """Return whether the grammar bitmask helper carries the patch marker."""
    fn = getattr(module, "apply_grammar_bitmask", None)
    return fn is not None and getattr(fn, "_kunlun_patched", False)


def _apply_grammar_bitmask_patch(module: ModuleType) -> None:
    """Import the Kunlun grammar helper, which patches vLLM in place."""
    if hasattr(module, "apply_grammar_bitmask"):
        import vllm_kunlun.v1.structured_output.utils  # noqa: F401


# --- vllm.v1.worker.gpu_worker: skip the CUDA memory-pool context ----------


def _memory_pool_applied(module: ModuleType) -> bool:
    """Return whether the worker memory-pool context is already patched."""
    cls = getattr(module, "Worker", None)
    return cls is None or getattr(cls, "_kunlun_memory_pool_patched", False)


def _apply_memory_pool_patch(module: ModuleType) -> None:
    """Bypass vLLM's CUDA memory-pool context on Kunlun workers.

    CUDA memory pools do not exist on Kunlun devices.  The replacement keeps
    the original behavior on every other platform, so this patch is safe even
    in mixed deployments where the class is shared.
    """
    from contextlib import nullcontext

    original = module.Worker._maybe_get_memory_pool_context

    def patched(self, tag: str):
        from vllm.platforms import current_platform

        if type(current_platform).__name__ == "KunlunPlatform":
            return nullcontext()
        return original(self, tag)

    module.Worker._maybe_get_memory_pool_context = patched
    module.Worker._kunlun_memory_pool_patched = True
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] patched Worker._maybe_get_memory_pool_context"
    )


# --- vllm.model_executor.warmup.kernel_warmup: skip Triton warmup ----------


def _warmup_applied(module: ModuleType) -> bool:
    """Return whether the unsupported Qwen Triton warmup is disabled."""
    fn = getattr(module, "qwen_triton_warmup", None)
    return fn is not None and getattr(fn, "_kunlun_patched", False)


def _skip_qwen_triton_warmup(*args, **kwargs):
    """No-op replacement: the warmup only compiles Triton kernels, and
    Triton is unavailable on Kunlun."""
    logging.getLogger("vllm_kunlun").info("[KunlunPlugin] Skipping qwen_triton_warmup")


_skip_qwen_triton_warmup._kunlun_patched = True


def _apply_warmup_patch(module: ModuleType) -> None:
    """Replace vLLM's Qwen Triton warmup with the no-op helper."""
    module.qwen_triton_warmup = _skip_qwen_triton_warmup
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] patched kernel_warmup.qwen_triton_warmup -> no-op"
    )


# --- vllm.model_executor.custom_op: load Kunlun OOT registrations ----------


def _oot_registrations_applied(module: ModuleType) -> bool:
    """Return whether Kunlun out-of-tree operators finished registering."""
    # Without PluggableLayer this vLLM version predates the OOT registration
    # API, so there is nothing to register and the hook reports "done".
    if not hasattr(module, "CustomOp") or not hasattr(module, "PluggableLayer"):
        return True
    ops_module = sys.modules.get("vllm_kunlun.ops")
    return bool(getattr(ops_module, "_KUNLUN_OOT_REGISTRATIONS_LOADED", False))


def _apply_oot_registrations(module: ModuleType) -> None:
    """Import Kunlun operators so their registration decorators execute."""
    import vllm_kunlun.ops  # noqa: F401


# --- compressed_tensors int8 MoE: disable the CUDA backend selector --------


def _int8_moe_applied(module: ModuleType) -> bool:
    """Return whether the compressed-tensors INT8 selector was replaced."""
    if not hasattr(module, "select_int8_moe_backend"):
        return False
    return getattr(module, "_kunlun_select_int8_patched", False)


def _select_int8_moe_backend(config, weight_key=None, activation_key=None):
    """Report no dedicated INT8 MoE backend.

    The upstream selector only knows CUDA backends.  Returning ``(None,
    None)`` steers vLLM to the generic path, where Kunlun's own
    compressed-tensors implementation takes over.
    """
    return None, None


def _apply_int8_moe_patch(module: ModuleType) -> None:
    """Replace vLLM's INT8 MoE backend selector with the Kunlun fallback."""
    if not hasattr(module, "select_int8_moe_backend"):
        return
    module.select_int8_moe_backend = _select_int8_moe_backend
    module._kunlun_select_int8_patched = True


# --- vllm.model_executor.models.deepseek_v2: Indexer  ----


def _indexer_applied(module: ModuleType) -> bool:
    """Return whether indexer hook is already patched.

    1. DeepseekV32IndexerCache.get_attn_backend -> Kunlun backend
    2. per_token_group_quant_fp8 -> indexer_quant2d
    3. mla.indexer prefill metadata kernel -> Torch replacement
    """
    cls = getattr(module, "DeepseekV32IndexerCache", None)
    if cls is None:
        return True

    backend_fn = getattr(cls, "get_attn_backend", None)
    backend_ok = getattr(backend_fn, "_kunlun_patched", False)
    quant_fn = getattr(module, "per_token_group_quant_fp8", None)
    quant_ok = getattr(quant_fn, "_kunlun_patched", False)
    indexer_mod = sys.modules.get("vllm.v1.attention.backends.mla.indexer")
    kernel = getattr(indexer_mod, "_build_prefill_chunk_metadata_kernel", None)
    kernel_ok = getattr(kernel, "_kunlun_patched", False)

    return backend_ok and quant_ok and kernel_ok


def _apply_indexer_patch(module: ModuleType) -> None:
    """Replace vLLM's DeepseekV32IndexerCache.get_attn_backend() which always
    returns DeepseekV32IndexerBackend with the Kunlun fallback."""
    cls = getattr(module, "DeepseekV32IndexerCache", None)
    if cls is None:
        return
    from vllm_kunlun.v1.attention.backends.mla.indexer import (
        KunlunDeepseekV32IndexerBackend,
        patch_prefill_chunk_metadata_kernel,
    )

    # Importing the Kunlun indexer has already loaded
    # vllm.v1.attention.backends.mla.indexer. Replace its Triton
    # _BUILD_PREFILL_CHUNK_METADATA_KERNEL now so build() does not launch
    # a kernel Kunlun cannot run.
    patch_prefill_chunk_metadata_kernel()

    # Replace the indexer quant with the Kunlun implementation.
    from vllm_kunlun.ops.sparse_attn_indexer import indexer_quant2d

    indexer_quant2d._kunlun_patched = True
    module.per_token_group_quant_fp8 = indexer_quant2d
    logging.getLogger("vllm_kunlun").info(
        "[KunlunPlugin] patched deepseek Indexer fp8 quant"
    )

    def get_attn_backend(self):
        return KunlunDeepseekV32IndexerBackend

    get_attn_backend._kunlun_patched = True
    cls.get_attn_backend = get_attn_backend


# --- Model Runner V2: torch-native replacements for the Triton kernels ----


def _resolve(module: ModuleType, path: str):
    """Follow a dotted attribute path from ``module``; None if any step misses."""
    obj = module
    for part in path.split("."):
        obj = getattr(obj, part, None)
        if obj is None:
            return None
    return obj


def _v2_hook(kunlun_module: str, *paths: str):
    """Build an ``*_applied`` / ``_apply_*`` pair for one Model Runner V2 module.

    Kunlun cannot run the Triton kernels the V2 model runner launches, so each
    launch site is rebound to a torch-native (or ``kunlun_ops``) equivalent.
    Every replacement lives in a module under ``vllm_kunlun.v1.worker.gpu`` that
    installs its own overrides on import, so applying a patch is just importing
    that module -- the "import-for-side-effect" style described above.

    ``paths`` are dotted attribute paths into the *upstream* module naming
    objects the replacement always installs (e.g.
    ``"BlockTables.gather_block_tables"``).  The patch counts as applied once
    every one of them resolves to an object defined under ``vllm_kunlun``.
    Deriving that from ``__module__`` instead of a marker attribute keeps the
    predicate self-healing and needs no bookkeeping in the replacements: an
    object still owned by upstream is, by definition, not yet patched.

    Paths that resolve to nothing are skipped rather than reported as pending,
    following the convention above -- a symbol upstream no longer has is
    "nothing to do", not an error.
    """

    def applied(module: ModuleType) -> bool:
        for path in paths:
            obj = _resolve(module, path)
            if obj is None:
                continue
            if not getattr(obj, "__module__", "").startswith("vllm_kunlun"):
                return False
        return True

    def apply_patch(module: ModuleType) -> None:
        importlib.import_module(kunlun_module)

    return applied, apply_patch


# Upstream V2 module -> (Kunlun replacement, sentinel attribute paths).
# Spec-decode (rejection_sampler_utils) is a deferred milestone: its Triton
# kernels are left alone and the V2 spec-decode path stays unsupported.
_V2_PATCHES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "vllm.v1.worker.gpu.buffer_utils",
        "vllm_kunlun.v1.worker.gpu.buffer_utils",
        ("StagedWriteTensor.apply_write", "FusedStagedWriter.apply"),
    ),
    (
        "vllm.v1.worker.gpu.block_table",
        "vllm_kunlun.v1.worker.gpu.block_table",
        (
            "BlockTables.apply_staged_writes",
            "BlockTables.gather_block_tables",
            "BlockTables.compute_slot_mappings",
        ),
    ),
    (
        "vllm.v1.worker.gpu.input_batch",
        "vllm_kunlun.v1.worker.gpu.input_batch",
        (
            "prepare_prefill_inputs",
            "prepare_pos_seq_lens",
            "combine_sampled_and_draft_tokens",
            "get_num_sampled_and_rejected",
            "post_update",
            "post_update_num_computed_tokens",
            "expand_idx_mapping",
        ),
    ),
    (
        "vllm.v1.worker.gpu.structured_outputs",
        "vllm_kunlun.v1.worker.gpu.structured_outputs",
        ("StructuredOutputsWorker.apply_grammar_bitmask",),
    ),
    (
        "vllm.v1.worker.gpu.sample.gumbel",
        "vllm_kunlun.v1.worker.gpu.sample.gumbel",
        ("apply_temperature", "gumbel_sample"),
    ),
    (
        "vllm.v1.worker.gpu.sample.min_p",
        "vllm_kunlun.v1.worker.gpu.sample.min_p",
        ("apply_min_p",),
    ),
    (
        "vllm.v1.worker.gpu.sample.penalties",
        "vllm_kunlun.v1.worker.gpu.sample.penalties",
        ("apply_penalties", "bincount"),
    ),
    (
        "vllm.v1.worker.gpu.sample.logit_bias",
        "vllm_kunlun.v1.worker.gpu.sample.logit_bias",
        ("apply_logit_bias",),
    ),
    (
        "vllm.v1.worker.gpu.sample.bad_words",
        "vllm_kunlun.v1.worker.gpu.sample.bad_words",
        ("apply_bad_words",),
    ),
    (
        "vllm.v1.worker.gpu.sample.logprob",
        "vllm_kunlun.v1.worker.gpu.sample.logprob",
        ("compute_token_logprobs", "compute_topk_logprobs"),
    ),
    (
        "vllm.v1.worker.gpu.sample.prompt_logprob",
        "vllm_kunlun.v1.worker.gpu.sample.prompt_logprob",
        ("get_prompt_logprobs_token_ids",),
    ),
    # Multimodal M-RoPE / XD-RoPE position preparation (every Qwen-VL model).
    (
        "vllm.v1.worker.gpu.mm.rope",
        "vllm_kunlun.v1.worker.gpu.mm.rope",
        ("RopeState.prepare_positions",),
    ),
    # Hybrid attention + mamba model state (Qwen3-Next, Qwen3.5, ...).  Only
    # reached when model_config.is_hybrid, via model_states/__init__.py:31.
    # The Kunlun GDN builder rebind in that module is best-effort and so is
    # deliberately not a sentinel here.
    (
        "vllm.v1.worker.gpu.model_states.mamba_hybrid",
        "vllm_kunlun.v1.worker.gpu.model_states.mamba_hybrid",
        ("_scatter_num_accepted_kernel",),
    ),
    # Shared by V1 and V2: xspeedgate batch_memcpy + int64 copy buffers.
    (
        "vllm.v1.worker.mamba_utils",
        "vllm_kunlun.v1.worker.mamba_utils",
        ("batch_memcpy", "MambaCopyBuffers.create"),
    ),
)


# (target module, is_applied, apply_patch) triples registered by import_hooks.
DEFAULT_HOOKS = (
    ("vllm.config.vllm", _mrv2_gate_applied, _apply_mrv2_gate),
    (
        "vllm.utils.import_utils",
        _optional_dep_probe_applied,
        _apply_optional_dep_probe,
    ),
    ("vllm.v1.worker.utils", _kv_block_zeroer_applied, _apply_kv_block_zeroer),
    (
        "vllm.v1.attention.backends.mla.prefill.registry",
        _mla_prefill_backend_applied,
        _apply_mla_prefill_backend,
    ),
    (
        "vllm.v1.worker.gpu_model_runner",
        _bind_kv_cache_applied,
        _apply_bind_kv_cache,
    ),
    (
        "vllm.model_executor.models.qwen3_vl",
        _qwen3_vl_applied,
        _apply_qwen3_vl_patch,
    ),
    (
        "vllm.model_executor.layers.minimax_rms_norm.rms_norm_tp",
        _minimax_rms_norm_tp_applied,
        _apply_minimax_rms_norm_tp_patch,
    ),
    ("vllm.v1.worker.block_table", _block_table_applied, _apply_block_table_patch),
    (
        "vllm.v1.structured_output.utils",
        _grammar_bitmask_applied,
        _apply_grammar_bitmask_patch,
    ),
    ("vllm.v1.worker.gpu_worker", _memory_pool_applied, _apply_memory_pool_patch),
    (
        "vllm.model_executor.warmup.kernel_warmup",
        _warmup_applied,
        _apply_warmup_patch,
    ),
    (
        "vllm.model_executor.custom_op",
        _oot_registrations_applied,
        _apply_oot_registrations,
    ),
    (
        "vllm.model_executor.layers.quantization.compressed_tensors."
        "compressed_tensors_moe.compressed_tensors_moe_w8a8_int8",
        _int8_moe_applied,
        _apply_int8_moe_patch,
    ),
    (
        "vllm.model_executor.models.deepseek_v2",
        _indexer_applied,
        _apply_indexer_patch,
    ),
) + tuple(
    (target, *_v2_hook(kunlun_module, *paths))
    for target, kunlun_module, paths in _V2_PATCHES
)
